CREATE TABLE IF NOT EXISTS CITY (id BIGINT PRIMARY KEY, name varchar(100));
CREATE TABLE IF NOT EXISTS PLACE (id BIGINT PRIMARY KEY, address VARCHAR(100), city BIGINT, FOREIGN KEY (city) REFERENCES CITY(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS PHOTOGRAPHER (id BIGINT PRIMARY KEY, name VARCHAR(50), expirence INT, site VARCHAR(250));
CREATE TABLE IF NOT EXISTS PHOTO (id BIGINT PRIMARY KEY, name VARCHAR(50), path VARCHAR(250), photographer INT, FOREIGN KEY (photographer) REFERENCES PHOTOGRAPHER(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS FOOTBALLEVENT (id BIGINT PRIMARY KEY, name VARCHAR(50), date VARCHAR(50), time VARCHAR(50), price VARCHAR(50), photos ARRAY, place BIGINT, team1 VARCHAR(100), team2 VARCHAR(100), FOREIGN KEY (place) REFERENCES PLACE(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS ITEVENT (id BIGINT PRIMARY KEY,name VARCHAR(50),date VARCHAR(50),time VARCHAR(50),price VARCHAR(50),photos ARRAY,place BIGINT,stack VARCHAR(100),FOREIGN KEY (place) REFERENCES PLACE(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS MUSICEVENT (id BIGINT PRIMARY KEY,name VARCHAR(50),date VARCHAR(50),time VARCHAR(50),price VARCHAR(50),photos ARRAY,place BIGINT,artist VARCHAR(100),FOREIGN KEY (place) REFERENCES PLACE(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS TICKETEVENT (id BIGINT PRIMARY KEY,eventId BIGINT,eventType VARCHAR(100));
CREATE TABLE IF NOT EXISTS TICKET (id BIGINT PRIMARY KEY,buyerName VARCHAR(50),payTime VARCHAR(100),event BIGINT,FOREIGN KEY (event) REFERENCES TICKETEVENT(id) ON DELETE CASCADE);